# This file is *NOT* reloaded automatically

# Site variables
# Can create custom variables, accessible via {{ site.myvariable }}
title: William G Underwood
author: William G Underwood
email: wgu21@cam.ac.uk
description: Welcome to my website.
baseurl: ""
url: 'https://wgunderwood.github.io/'

# Build settings
theme: minima
show_excerpts: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag

highlighter: rouge

# Theme settings
minima:
  date_format: "%d %B %Y"

header_pages:
  - publications.markdown
  - posts.markdown
  - contact.markdown

# Exclude from build
exclude:
- code
- Gemfile
- Gemfile.lock
- Makefile
- notes.org
- README.md
- vendor
